; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+08 on Fri Nov 12 2021 20:40:13 GMT+0000 (Greenwich Mean Time)

