; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+08 on Fri Nov 12 2021 20:40:13 GMT+0000 (Greenwich Mean Time)
; Wait for set temperatures to be reached
M116 P0

